package com.MobyDickens.model;

/**
 * Created by Brad on 11/20/2016.
 */
public enum Genre {
    NON_FICTION, ROMANCE, HORROR, YOUNG_ADULT, SCIENCE_FICTION, COMEDY, DRAMA, SATIRE, TRAGEDY, FANTASY, FABLE, FAIRY_TALE,
    CRIME_DETECTIVE, MYSTERY, FAN_FICTION, CLASSICS, REALISTIC_FICTION, HISTORICAL_FICTION, WESTERN, THRILLER, MANGA, ADVENTURE;
}